Sprint1
ClevertecFrontendLab/sprint1-ArtemDerenok pull request #1
Opened 2023-01-29 18:24 UTC by ArtemDerenok

2023-01-29 18:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675016796/content-window.png)

2023-01-29 18:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017045/content-window.png)

2023-01-29 18:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675017082/content-window.png)

2023-01-29 18:45 UTC, Gaurrus requested changes

2023-01-29 18:45 UTC, Gaurrus commented on src/components/filtration/filtration-bar.tsx
> +        </svg>
так страшненькл, можно просто в img вставить)

2023-01-29 18:45 UTC, Gaurrus commented on src/components/layout/layout.module.scss
> +  height: 100%;
т.к. layout скорее всего вложен во что то без высоты, то 100% высоты ему взять неоткуда поэтому 
![image](https://user-images.githubusercontent.com/85307211/215348475-8c6fdf92-abe1-4f16-b1cb-c52b58bdf3d9.png)
вот такие скриншоты - попробуй  `min-heigth: 100vh;` здесь, закинь изменения посмотрим скриншоты

2023-01-29 19:45 UTC, ArtemDerenok commented on src/components/filtration/filtration-bar.tsx
> +        </svg>
ну, я таким образом менял цвета в svg при наведении

2023-01-29 19:47 UTC, ArtemDerenok commented on src/components/layout/layout.module.scss
> +  height: 100%;
исправил

2023-01-29 19:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675021645/content-window.png)

2023-01-29 19:48 UTC, Gaurrus commented on src/components/filtration/filtration-bar.tsx
> +        </svg>
а ок, я бы средствами css это сделал

2023-01-29 19:48 UTC, Gaurrus requested changes

2023-01-29 19:48 UTC, Gaurrus commented on src/components/layout/layout.module.scss
> +  max-height: 100vh;
ага) только не max a min)

2023-01-29 19:52 UTC, ArtemDerenok commented on src/components/layout/layout.module.scss
> +  max-height: 100vh;
Точно)

2023-01-29 19:52 UTC, ArtemDerenok commented on src/components/filtration/filtration-bar.tsx
> +        </svg>
мне показалось, что так проще)

2023-01-29 19:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675022041/content-window.png)

2023-01-29 20:35 UTC, Gaurrus requested changes

2023-01-29 20:35 UTC, Gaurrus commented on src/index.scss
> +  height: 100%;
вроде нашел, вот это зря добавлял, убирай - будем смотреть скриншоты)

2023-01-29 21:08 UTC, ArtemDerenok commented on src/index.scss
> +  height: 100%;
убрал

2023-01-29 21:09 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675026568/content-window.png)

2023-01-30 06:14 UTC, Gaurrus requested changes

2023-01-30 06:14 UTC, Gaurrus commented on package.json
>    },
![image](https://user-images.githubusercontent.com/85307211/215399118-6b9fe9d1-4eb1-4ff9-8c6f-6ead60e6c446.png)
на 320 у тебя явно горизонтальный скролл - кнопка не помещается, горизонтальных скроллов быть вообще нигде не должно

2023-01-30 06:14 UTC, Gaurrus commented on package.json
>    "dependencies": {
![image](https://user-images.githubusercontent.com/85307211/215400482-99590291-b7e8-47c7-9f6f-3c3e218cc752.png)
фото книги маловато, в дизайне не так

2023-01-30 06:14 UTC, Gaurrus commented on package.json
>      "mochawesome": "^7.1.3",
![image](https://user-images.githubusercontent.com/85307211/215400771-77584e2e-e800-4c16-a0c0-3e6c57749927.png)
сама карточка слишком уменьшилась, и фото не по центру, сверься с дизайном

2023-01-30 06:14 UTC, Gaurrus commented on package.json
>      "react": "^18.2.0",
![image](https://user-images.githubusercontent.com/85307211/215400958-f6317b37-0080-45f4-b0de-a789209b19e5.png)
здесь тоже карточки слишком маленькие и поэтому не похоже на то что в дизайне - пересмотри

2023-01-30 06:14 UTC, Gaurrus commented on package.json
>      "react-dom": "^18.2.0",
![image](https://user-images.githubusercontent.com/85307211/215401566-cb71f3ea-88db-4963-b2c3-f769cbef0251.png)
вообще саму карточку изначально посмотри, потому что везде не по центру фото

2023-01-30 08:39 UTC, ArtemDerenok commented on package.json
>      "react-dom": "^18.2.0",
исправил

2023-01-30 08:40 UTC, ArtemDerenok commented on package.json
>    "dependencies": {
исправил

2023-01-30 08:41 UTC, ArtemDerenok commented on package.json
>    },
Странно. Перепроверил, вроде все нормально

2023-01-30 08:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675068076/content-window.png)

2023-01-30 08:46 UTC, Gaurrus requested changes

2023-01-30 08:46 UTC, Gaurrus commented on package.json
>      "react-router-dom": "^6.4.2",
карточку поправил, а остальные замечания? 320 ширина вообще плохо, пройдись внимательно по тем замечаниям которые были оставлены в прошлый раз!)

2023-01-30 09:12 UTC, ArtemDerenok commented on package.json
>      "react": "^18.2.0",
Исправил. Размер карточек в норме, меньше ширина контейнера должна быть

2023-01-30 09:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675069994/content-window.png)

2023-01-30 09:35 UTC, Gaurrus commented on package.json
>      "react-router-dom": "^6.4.2",
https://user-images.githubusercontent.com/85307211/215439645-b7a9bd24-3173-4ca6-9796-d3c58735f3c5.mp4

он кастомный и его плохо видно, вот видео, и запускай сначала локально перед коммитом тесты в папке \cypress\report\screenshots\ все свои скриншоты смотри, - должно быть максимално похоже на макет фигмы, не спами каждое мелкое изменение коммитом - сделай все замечания потом запуш

2023-01-30 09:37 UTC, Gaurrus requested changes
прикрепил видео где видно скролл в нашей переписке

2023-01-30 12:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675082343/content-window.png)

2023-01-30 13:02 UTC, Gaurrus requested changes
вот еще 2 вещи исправляй, как испоавишь - смотрю код и апрувим)

2023-01-30 20:50 UTC, ArtemDerenok commented on package.json
>      "react-scripts": "^5.0.1",
есть

2023-01-30 20:50 UTC, ArtemDerenok commented on package.json
>      "web-vitals": "^3.0.3"
добавил text-overflow

2023-01-30 20:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtemDerenok/1675111937/content-window.png)

2023-01-31 06:04 UTC, Gaurrus approved these changes

2023-01-31 07:54 UTC, merged